name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings -D clippy::dbg_macro

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  cargo-verifications:
    needs: cancel-previous-runs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - command: fmt
            args: --all --verbose -- --check
          - command: clippy
            args: --all-targets --all-features
          - command: check
            args: --all-targets
          - command: check
            args: --all-targets --all-features
          - command: check
            args: --verbose --target thumbv6m-none-eabi --no-default-features
          - command: check
            args: --verbose --target thumbv6m-none-eabi --no-default-features --features alloc
          - command: check
            args: --verbose --target thumbv6m-none-eabi --no-default-features --features serde
          - command: test
            args: --all-targets --all-features
          - command: test
            args: --all-targets --no-default-features
          - command: test
            args: --all-targets --no-default-features --features serde
          - command: test
            args: --all-targets --no-default-features --features alloc
          - command: test
            args: --all-targets --features serde
    steps:
      - run: echo "pass"
